### PR TITLE
Fix declaration of dt_saved_value in ISPC backend

### LINKED ISSUE #329: Issue with variable definition for ISPC backend
During compilation of https://github.com/Neurosim-lab/netpyne/blob/coreneuron/examples/coreneuron/m1/mod/kctin.mod there is a wrong definition of `dt_saved_value` from the generated code as `double` instead of `double uniform`.

```
x86_64/core/mod2c/kctin.ispc:142:19: Error: Can't convert from type "varying double" to type "uniform double" for
        assignment operator.
        nt->_dt = dt_saved_value;
                  ^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by iomaganaris**
- `dt_saved_value` should be defined as uniform in the ISPC backend while other variables should be varying (simply double)
- Fixes #329

### CODE REVIEW

File: src/codegen/codegen_ispc_visitor.cpp [hunk 1]
```diff
@@ -63,6 +63,39 @@ void CodegenIspcVisitor::visit_var_name(ast::VarName& node) {
...
 
+void CodegenIspcVisitor::visit_local_list_statement(ast::LocalListStatement& node) {
+    if (!codegen) {
+        return;
+    }
+    auto type = CodegenCVisitor::local_var_type() + " ";
+    printer->add_text(type);
+    auto local_variables = node.get_variables();
+    std::set<std::string> uniform_variables;
+    auto dt_saved_value_exists = false;
```
Comment (tristan0x) [inline src/codegen/codegen_ispc_visitor.cpp:74]:
```suggestion
    bool dt_saved_value_exists = false;
```

File: src/codegen/codegen_ispc_visitor.cpp [hunk 2]
```diff
@@ -63,6 +63,39 @@ void CodegenIspcVisitor::visit_var_name(ast::VarName& node) {
...
+
+    /// Remove dt_saved_value from local_variables if it exists
+    for (auto it_local_variables = local_variables.begin();
+         it_local_variables < local_variables.end();
+         ++it_local_variables) {
+        if ((*it_local_variables)->get_node_name() == "dt_saved_value") {
+            local_variables.erase(it_local_variables);
```
Comment (tristan0x) [inline src/codegen/codegen_ispc_visitor.cpp:81]: `std::vector<T>::erase` invalidates iterators.

```suggestion
            it_local_variables = local_variables.erase(it_local_variables);
```

I would replace the for loop with a `std::remove_if` though.

File: src/codegen/codegen_ispc_visitor.cpp [hunk 3]
```diff
@@ -63,6 +63,39 @@ void CodegenIspcVisitor::visit_var_name(ast::VarName& node) {
...
+    printer->add_text(type);
+    auto local_variables = node.get_variables();
+    std::set<std::string> uniform_variables;
+    auto dt_saved_value_exists = false;
+
+    /// Remove dt_saved_value from local_variables if it exists
+    for (auto it_local_variables = local_variables.begin();
+         it_local_variables < local_variables.end();
+         ++it_local_variables) {
+        if ((*it_local_variables)->get_node_name() == "dt_saved_value") {
```
Comment (tristan0x) [inline src/codegen/codegen_ispc_visitor.cpp:80]: I would use a constant instead of the hardcoded string `dt_saved_value`.

File: src/codegen/codegen_ispc_visitor.cpp [hunk 4]
```diff
@@ -63,6 +63,39 @@ void CodegenIspcVisitor::visit_var_name(ast::VarName& node) {
...
 }
 
+void CodegenIspcVisitor::visit_local_list_statement(ast::LocalListStatement& node) {
+    if (!codegen) {
+        return;
+    }
+    auto type = CodegenCVisitor::local_var_type() + " ";
+    printer->add_text(type);
+    auto local_variables = node.get_variables();
+    std::set<std::string> uniform_variables;
```
Comment (tristan0x) [inline src/codegen/codegen_ispc_visitor.cpp:73]: `uniform_variables` variable seems unused

File: src/codegen/codegen_ispc_visitor.cpp (hunk 3 above)
Comment (iomaganaris) [reply src/codegen/codegen_ispc_visitor.cpp:80]: Good point. I added it as a constant and some documentation on how this name is generated 👍

File: src/codegen/codegen_ispc_visitor.cpp (hunk 4 above)
Comment (iomaganaris) [reply src/codegen/codegen_ispc_visitor.cpp:73]: True. I missed it 😞

File: src/codegen/codegen_ispc_visitor.cpp (hunk 2 above)
Comment (iomaganaris) [reply src/codegen/codegen_ispc_visitor.cpp]: You're right. Fixed that. 👍

**Comment by iomaganaris** [comment]
> Is it possible to easily add a UT for this?

I am in favour of adding a test for this however it's not very easy to do so, since this is used in the code generation of the `.ispc` file and we don't have set up a system for testing the code generation. 
It makes a lot of sense to add an integration test which tests this but it's not merged yet (PR #346 ).  I can keep a note in the related issue and add a test when it is merged.
For now I can just provide the different output:
Before:
```
        inst->ist[id] = kctin_global.ist0;
                double dt_saved_value, old_cst, old_ost;
        dt_saved_value = nt->_dt;
```
After:
```
        inst->ist[id] = kctin_global.ist0;

        double old_cst, old_ost;
        double uniform dt_saved_value;
        dt_saved_value = nt->_dt;
```
