### PR TITLE
Check that token is not nullptr

### LINKED ISSUE #53: Symtabvisitor try to dereference nullptr token
If we add new global block in the AST without token and then run symtab visitor then we get segfault from:

```c++
void SymtabVisitor::add_model_symbol_with_property(ast::Node* node, NmodlType property) {
    auto token = node->get_token();   => nullptr !
    auto name = node->get_node_name();
    auto symbol = std::make_shared<Symbol>(name, node, *token);
```

### PR DESCRIPTION
**Pull request by alkino**
Fix #53

### CODE REVIEW

File: src/visitors/symtab_visitor_helper.hpp [hunk 1]
```diff
@@ -149,6 +149,9 @@ void SymtabVisitor::setup_symbol(ast::Node* node, NmodlType property) {
 
 void SymtabVisitor::add_model_symbol_with_property(ast::Node* node, NmodlType property) {
     auto token = node->get_token();
+    if (!token) { // token can be nullptr
+        return;
+    }
```
Comment (pramodk) [inline src/visitors/symtab_visitor_helper.hpp:154]: @alkino : I believe in this case we need to add `node` to symbol table but with "default" `ModToken` object (i.e. token which will not have location information associated with it).

Otherwise, here we are just skipping adding symbol in the symbol table which means we will not find that symbol and that might be problematic somewhere else.

**Review by pramodk — CHANGES_REQUESTED** [review]

**Review by pramodk — APPROVED** [review]
