### PR TITLE
Fixed for watch statements codegen, global and NetSendBuffer_t variables  update on CPU/GPU

### LINKED ISSUE #675: NMODL does not produce correct results with OpenACC+GPU
NMODL generates OpenACC code from the [Gfluct3.mod](https://github.com/neuronsimulator/testcorenrn/blob/7b781b3a7ac1e0b785f897e4db5c3bf84c5127d2/mod/Gfluct3.mod) mechanism that gives incorrect results. This leads to test failures when the NEURON test suite is run using CoreNEURON and NMODL, i.e.
```sh
cmake ..  -DNRN_ENABLE_TESTS=ON -DNRN_ENABLE_CORENEURON=ON -DCORENRN_ENABLE_GPU=ON -DCORENRN_ENABLE_NMODL=ON
cmake --build . --parallel
ctest -j 8
```

The `testcorenrn_gf::compare_results` test fails because the output spikes from `testcorenrn_gf::coreneuron_gpu_online` and `testcorenrn_gf::coreneuron_gpu_offline` do not match NEURON and the reference file.

The following diff, which was inspired by comparing the NMODL and MOD2C translations of this `.mod` file, fixes the `testcorenrn_gf` test for NMODL+GPU. This might not be a **minimal** patch, and the part related to https://github.com/BlueBrain/nmodl/issues/680 should be considered separately and discussed in that issue.
```diff
--- generated/Gfluct3.cpp	2021-05-31 14:27:33.065048143 +0200
+++ modified/Gfluct3.cpp	2021-05-31 14:27:13.992794000 +0200
@@ -462,9 +462,10 @@
​
​
     static inline void net_send_buffering(NetSendBuffer_t* nsb, int type, int vdata_index, int weight_index, int point_index, double t, double flag)  {
-        int i = nsb->_cnt;
-        nsb->_cnt++;
-        if(nsb->_cnt >= nsb->_size) {
+        int i = 0;
+    #pragma acc atomic capture
+        i = nsb->_cnt++;
+        if(i >= nsb->_size) {
             printf("Error : netsend buffer size (%d) exceeded\n", nsb->_cnt);
             coreneuron_abort();
         }
@@ -546,8 +547,10 @@
                     net_receive_kernel_Gfluct3(t, point_process, inst, nt, ml, weight_index, flag);
                 }
             }
-
+            #pragma acc wait(nt->stream_id)
             NetSendBuffer_t* nsb = ml->_net_send_buffer;
+            #pragma acc update self(nsb->_cnt) if(nt->compute_gpu)
+            update_net_send_buffer_on_host(nt, nsb);
             for (int i=0; i < nsb->_cnt; i++) {
                 int type = nsb->_sendtype[i];
                 int tid = nt->id;
@@ -559,7 +562,7 @@
                 net_sem_from_gpu(type, vdata_index, weight_index, tid, point_index, t, flag);
             }
             nsb->_cnt = 0;
-
+            #pragma acc update device(nsb->_cnt) if (nt->compute_gpu)
             nrb->_displ_cnt = 0;
             nrb->_cnt = 0;
         }
@@ -630,11 +633,27 @@
                         inst->amp_i[id] = inst->std_i[id] * sqrt((1.0 - exptrap_in_1));
                     }
                     if ((inst->tau_e[id] != 0.0) || (inst->tau_i[id] != 0.0)) {
-                        net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[3*pnodecount+id], -1, inst->point_process[1*pnodecount+id], nt->_t+inst->h[id], 1.0);
+                        net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[3*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+inst->h[id], 1.0);
                     }
                 }
             }
         }
+        #pragma acc wait(nt->stream_id)
+        NetSendBuffer_t* nsb = ml->_net_send_buffer;
+        #pragma acc update self(nsb->_cnt) if(nt->compute_gpu)
+        update_net_send_buffer_on_host(nt, nsb);
+        for (int i=0; i < nsb->_cnt; i++) {
+            int type = nsb->_sendtype[i];
+            int tid = nt->id;
+            double t = nsb->_nsb_t[i];
+            double flag = nsb->_nsb_flag[i];
+            int vdata_index = nsb->_vdata_index[i];
+            int weight_index = nsb->_weight_index[i];
+            int point_index = nsb->_pnt_index[i];
+            net_sem_from_gpu(type, vdata_index, weight_index, tid, point_index, t, flag);
+        }
+        nsb->_cnt = 0;
+        #pragma acc update device(nsb->_cnt) if (nt->compute_gpu)
     }
```

cc: @pramodk @iomaganaris

### LINKED ISSUE #678: NMODL does not update global variables on GPU
NMODL generates OpenACC code from the [hhwatch.mod](https://github.com/neuronsimulator/testcorenrn/blob/7b781b3a7ac1e0b785f897e4db5c3bf84c5127d2/mod/hhwatch.mod) mechanism that gives incorrect results. This leads to test failures when the NEURON test suite is run using CoreNEURON and NMODL, i.e.
```sh
cmake ..  -DNRN_ENABLE_TESTS=ON -DNRN_ENABLE_CORENEURON=ON -DCORENRN_ENABLE_GPU=ON -DCORENRN_ENABLE_NMODL=ON
cmake --build . --parallel
ctest -j 8
```
The `testcorenrn_watch::compare_results` test fails because the output spikes from the CoreNEURON+GPU tests do not match the NEURON and CoreNEURON+CPU runs, and the reference file. In the current `master` this is affected by https://github.com/BlueBrain/nmodl/issues/675, but if that is worked around there is a second issue: these tests [configure non-default values for some global parameters](https://github.com/neuronsimulator/testcorenrn/blob/7b781b3a7ac1e0b785f897e4db5c3bf84c5127d2/testwatch.hoc#L17-L19), and these values are not updated on the GPU. The OpenACC code generated by NMODL should include:
```diff
     /** initialize channel */
     void nrn_init_hhwatch(NrnThread* nt, Memb_list* ml, int type) {
+        #pragma acc update device (hhwatch_global) if(nt->compute_gpu)
         #pragma acc data present(nt, ml, hhwatch_global) if(nt->compute_gpu)
         {
```
to ensure the device-side values of these parameters are updated.

The full diff of manual changes to the generate C++ file that was tested locally is shown below. This includes three different sets of changes:
- [ ] Workarounds for https://github.com/BlueBrain/nmodl/issues/675
- [x] Changes to the `if ( ... ) { ... } else { ... }` structure of the `nrn_watch_check_...` method to match MOD2C's generate code, see https://github.com/BlueBrain/nmodl/issues/679)
- [x] The global variable fix (`#pragma acc update device (hhwatch_global) if(nt->compute_gpu)`) noted above
- [ ] MOD2C's behaviour is adopted for https://github.com/BlueBrain/nmodl/issues/680
- [ ] Also bring changes from PR BlueBrain/mod2c#63 mentioned in 679
-
The **full** diff:
```diff
--- hhwatch-original.cpp 2021-06-01 09:31:52.879278000 +0200
+++ hhwatch-patched.cpp  2021-06-01 09:27:37.270874000 +0200
@@ -230,9 +230,10 @@


     static inline void net_send_buffering(NetSendBuffer_t* nsb, int type, int vdata_index, int weight_index, int point_index, double t, double flag)  {
-        int i = nsb->_cnt;
-        nsb->_cnt++;
-        if(nsb->_cnt >= nsb->_size) {
+        int i = 0;
+#pragma acc atomic capture
+        i = nsb->_cnt++;
+        if(i >= nsb->_size) {
             printf("Error : netsend buffer size (%d) exceeded\n", nsb->_cnt);
             coreneuron_abort();
         }
@@ -291,49 +292,47 @@
                     if (v >  -55.0) {
                         if ((inst->watch1[4*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 2.0);
-                            inst->watch1[4*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch1[4*pnodecount+id] = 2;
                         }
+                        inst->watch1[4*pnodecount+id] = 3;
+                    } else {
+                        inst->watch1[4*pnodecount+id] = 2;
                     }
                 }
                 if (inst->watch2[5*pnodecount+id]&2) {
                     if (v > 10.0) {
                         if ((inst->watch2[5*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 3.0);
-                            inst->watch2[5*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch2[5*pnodecount+id] = 2;
                         }
+                        inst->watch2[5*pnodecount+id] = 3;
+                    } else {
+                        inst->watch2[5*pnodecount+id] = 2;
                     }
                 }
                 if (inst->watch3[6*pnodecount+id]&2) {
                     if (v <  -70.0) {
                         if ((inst->watch3[6*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 4.0);
-                            inst->watch3[6*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch3[6*pnodecount+id] = 2;
                         }
+                        inst->watch3[6*pnodecount+id] = 3;
+                    } else {
+                        inst->watch3[6*pnodecount+id] = 2;
                     }
                 }
                 if (inst->watch4[7*pnodecount+id]&2) {
                     if (v >  -55.0) {
                         if ((inst->watch4[7*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 2.0);
-                            inst->watch4[7*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch4[7*pnodecount+id] = 2;
                         }
+                        inst->watch4[7*pnodecount+id] = 3;
+                    } else {
+                        inst->watch4[7*pnodecount+id] = 2;
                     }
                 }
             }
-
             NetSendBuffer_t* nsb = ml->_net_send_buffer;
+            #pragma acc wait(nt->stream_id)
+            #pragma acc update self(nsb->_cnt) if(nt->compute_gpu)
+            update_net_send_buffer_on_host(nt, nsb);
             for (int i=0; i < nsb->_cnt; i++) {
                 int type = nsb->_sendtype[i];
                 int tid = nt->id;
@@ -345,6 +344,7 @@
                 net_sem_from_gpu(type, vdata_index, weight_index, tid, point_index, t, flag);
             }
             nsb->_cnt = 0;
+            #pragma acc update device(nsb->_cnt) if (nt->compute_gpu)
         }
     }

@@ -425,8 +425,12 @@
                     net_receive_kernel_hhwatch(t, point_process, inst, nt, ml, weight_index, flag);
                 }
             }
-
+            #pragma acc wait(nt->stream_id)
+            nrb->_displ_cnt = 0;
+            nrb->_cnt = 0;
             NetSendBuffer_t* nsb = ml->_net_send_buffer;
+            #pragma acc update self(nsb->_cnt) if(nt->compute_gpu)
+            update_net_send_buffer_on_host(nt, nsb);
             for (int i=0; i < nsb->_cnt; i++) {
                 int type = nsb->_sendtype[i];
                 int tid = nt->id;
@@ -438,15 +442,14 @@
                 net_sem_from_gpu(type, vdata_index, weight_index, tid, point_index, t, flag);
             }
             nsb->_cnt = 0;
-
-            nrb->_displ_cnt = 0;
-            nrb->_cnt = 0;
+            #pragma acc update device(nsb->_cnt) if (nt->compute_gpu)
         }
     }


     /** initialize channel */
     void nrn_init_hhwatch(NrnThread* nt, Memb_list* ml, int type) {
+        #pragma acc update device (hhwatch_global) if(nt->compute_gpu)
         #pragma acc data present(nt, ml, hhwatch_global) if(nt->compute_gpu)
         {
             int nodecount = ml->nodecount;
@@ -470,10 +473,26 @@
                     double v = voltage[node_id];
                     inst->g[id] = hhwatch_global.gpas;
                     inst->e[id] = hhwatch_global.erev;
-                    net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], -1, inst->point_process[1*pnodecount+id], nt->_t+0.0, 1.0);
+                    net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 1.0);
                 }
             }
         }
+        #pragma acc wait(nt->stream_id)
+        NetSendBuffer_t* nsb = ml->_net_send_buffer;
+        #pragma acc update self(nsb->_cnt) if(nt->compute_gpu)
+        update_net_send_buffer_on_host(nt, nsb);
+        for (int i=0; i < nsb->_cnt; i++) {
+            int type = nsb->_sendtype[i];
+            int tid = nt->id;
+            double t = nsb->_nsb_t[i];
+            double flag = nsb->_nsb_flag[i];
+            int vdata_index = nsb->_vdata_index[i];
+            int weight_index = nsb->_weight_index[i];
+            int point_index = nsb->_pnt_index[i];
+            net_sem_from_gpu(type, vdata_index, weight_index, tid, point_index, t, flag);
+        }
+        nsb->_cnt = 0;
+        #pragma acc update device(nsb->_cnt) if (nt->compute_gpu)
     }
```

### LINKED ISSUE #679: NMODL generates different WATCH statement logic to MOD2C
While investigating https://github.com/BlueBrain/nmodl/issues/678 we noticed that NMODL generates slightly different logic for `WATCH` statements than MOD2C. This does not affect the results of the `testcorenrn_watch` test in the NEURON CTest suite, but it may still be an issue that needs to be resolved.

The following diff modifies the code generated by NMODL to match the logic from MOD2C:
```diff
--- hhwatch-original.cpp 2021-06-01 09:31:52.879278000 +0200
+++ hhwatch-patched.cpp  2021-06-01 09:27:37.270874000 +0200
@@ -291,49 +292,47 @@
                     if (v >  -55.0) {
                         if ((inst->watch1[4*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 2.0);
-                            inst->watch1[4*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch1[4*pnodecount+id] = 2;
                         }
+                        inst->watch1[4*pnodecount+id] = 3;
+                    } else {
+                        inst->watch1[4*pnodecount+id] = 2;
                     }
                 }
                 if (inst->watch2[5*pnodecount+id]&2) {
                     if (v > 10.0) {
                         if ((inst->watch2[5*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 3.0);
-                            inst->watch2[5*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch2[5*pnodecount+id] = 2;
                         }
+                        inst->watch2[5*pnodecount+id] = 3;
+                    } else {
+                        inst->watch2[5*pnodecount+id] = 2;
                     }
                 }
                 if (inst->watch3[6*pnodecount+id]&2) {
                     if (v <  -70.0) {
                         if ((inst->watch3[6*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 4.0);
-                            inst->watch3[6*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch3[6*pnodecount+id] = 2;
                         }
+                        inst->watch3[6*pnodecount+id] = 3;
+                    } else {
+                        inst->watch3[6*pnodecount+id] = 2;
                     }
                 }
                 if (inst->watch4[7*pnodecount+id]&2) {
                     if (v >  -55.0) {
                         if ((inst->watch4[7*pnodecount+id]&1) == 0) {
                             net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 2.0);
-                            inst->watch4[7*pnodecount+id] = 3;
-                        }
-                        else {
-                            inst->watch4[7*pnodecount+id] = 2;
                         }
+                        inst->watch4[7*pnodecount+id] = 3;
+                    } else {
+                        inst->watch4[7*pnodecount+id] = 2;
                     }
                 }
             }
```

And, for example, the first block above generated by MOD2C (and re-formatted) is:
```c++
if (_watch_array(1)&2) {
  if  ( v > - 55.0 ) {
    if ((_watch_array(1)&1) == 0) {
      #if NET_RECEIVE_BUFFERING
      _net_send_buffering(_ml->_net_send_buffer, 0, _tqitem, 0, _ppvar[1*_STRIDE], t +  0.0 , 2.0 );
      #else
      net_send ( _tqitem, -1, (Point_process*) _nt->_vdata[_ppvar[1*_STRIDE]], t +  0.0 , 2.0 ) ;
      #endif
    }
    _watch_array(1) = 3;
  }else{
    _watch_array(1) = 2;
  }
}
```

And, for completeness, the vanilla code from NMODL is:
```c++
if (inst->watch1[4*pnodecount+id]&2) {
  if (v >  -55.0) {
    if ((inst->watch1[4*pnodecount+id]&1) == 0) {
      net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], 0, inst->point_process[1*pnodecount+id], nt->_t+0.0, 2.0);
      inst->watch1[4*pnodecount+id] = 3;
    } else {
      inst->watch1[4*pnodecount+id] = 2;
    }
  }
}
```

### LINKED ISSUE #680: NMODL and MOD2C pass different weight indices during initialisation
In the `nrn_init_...` method generated by NMODL for, for example, [Gfluct3.mod](https://github.com/neuronsimulator/testcorenrn/blob/7b781b3a7ac1e0b785f897e4db5c3bf84c5127d2/mod/Gfluct3.mod) there is a call
```c++
net_send_buffering(ml->_net_send_buffer, 0, inst->tqitem[2*pnodecount+id], -1, inst->point_process[1*pnodecount+id], nt->_t+0.0, 1.0);
```
where the 4th argument is `-1`, but in the MOD2C equivalent `0` is passed. This does not appear to have any effect on whether the tests pass, but it would be good to understand if this difference is a bug or not.

### PR DESCRIPTION
**Pull request by pramodk**
* fix watch statement code generation as described in #679
* fix global variable update to gpu descrbed in #678
* atomic capture for net_send buffer
* Initial block was missing net_send_buffering related codegen
   when net_send was used
* fix indentation with watch if-else statements
* net_buf_receive related code was out of place

Integration test from testcorenrn/hhwatch will be enabled in NEURON.

### todos 
- [x] changes from PR BlueBrain/mod2c#63 mentioned in 679
- [x] review/fix index argument passed to `net_send_buffering`
- [x] fix CVF CI: ISPC backend shouldn't have code for host/device update for net_send/receieve_buffering

Closes #679, closes #678, closes #675, closes #680

### CODE REVIEW

File: src/codegen/codegen_acc_visitor.hpp [hunk 1]
```diff
@@ -94,6 +94,18 @@ class CodegenAccVisitor: public CodegenCVisitor {
...
+    // update NetSendBuffer_t count from device to host
+    void print_net_send_buf_count_update_to_host() const override;
+
+    // update NetSendBuffer_t count from host to device
+    virtual void print_net_send_buf_count_update_to_device() const override;
+
+    // synchronise/wait on stream specific to NrnThread
+    virtual void print_device_stream_wait() const override;
+
+    // print aotmic capture pragma
```
Comment (olupton) [inline src/codegen/codegen_acc_visitor.hpp:106]:
```suggestion
    // print atomic capture pragma
```

**Review by olupton — COMMENTED** [review]
LGTM so far

**Review by olupton — APPROVED** [review]
LGTM, except I think https://github.com/BlueBrain/nmodl/issues/680 is not addressed so we should change the description so merging this doesn't automatically close it.

**Comment by pramodk** [comment]
> LGTM, except I think #680 is not addressed so we should change the description so merging this doesn't automatically close it.

Yeah, realised that after posting my previous comment. I am currently looking into that. If it's easy, I will fix it here. Otherwise, do that as a separate PR.

**Comment by pramodk** [comment]
Fixed #680 based on analysis in https://github.com/BlueBrain/nmodl/issues/680#issuecomment-885564763

**Review by iomaganaris — APPROVED** [review]
LGTM
