### PR TITLE
Fix incompatibility issues with manylinux1 platform

### LINKED ISSUE #319: Fix portability issues with wheel on manylinux1 platform
As we are targeting NMODL release with NEURON wheel, build the NMODL on manylinux1 platform and address any incompatibilities if any.

### PR DESCRIPTION
**Pull request by pramodk**
#### Motivation
We would like to ship nmodl with NEURON manylinux1 wheel during upcoming release 8.0 

#### Changes
- manylinux1 platform provides gcc 4.8.2 for wider compatibility
- gcc 4.8.2 is first gnu compiler supporting `almost all` C++11
  except that it lacks `const_iterator` overload for std::vector::erase
  and std::vector::insert
- in this PR we introduce const_iter_cast thar turns const iterator
  into non-const-iterator to have minimal changes to the code base
- change the compatibility to gcc 4.8.2 for cmake as well as json library
- change `pybind11::literals::operator""_a` to `namespace pybind11::literals`
  as documented in https://pybind11.readthedocs.io/en/stable/basics.html#keyword-arguments

fixes #319

#### Considerations
* This PR is **not an attempt** to bind to the oldest compiler
* We have [started investigation to upgrade to new gcc](https://github.com/neuronsimulator/nrn/issues/511) (e.g. v7 or v8) under manylinux platfor. This should happen soon after 8.0 release.
* For this 8.0 relate, NEURON wheel infrastructure is setup with manylinux1 and would be good to have current nmodl ship with NEURON
* As the changes are minimal here, it won't be a big deal to get this in.

### CODE REVIEW

File: src/utils/common_utils.hpp [hunk 1]
```diff
@@ -48,6 +48,32 @@ T remove_extension(T const& filename) {
...
+ *
+ * \todo Remove this after move to manylinux2010 platform.
+ */
+#if (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) < 40900
+template<typename T>
+typename std::vector<T>::iterator
+const_iter_cast(std::vector<T>& v, typename std::vector<T>::const_iterator iter) {
+    return v.begin() + (iter - v.cbegin());
+}
+#else
```
Comment (pramodk) [inline src/utils/common_utils.hpp:68]: I did this if-else logic so that newer compilers don’t need to use workaround solution.

File: src/utils/common_utils.hpp [hunk 2]
```diff
@@ -48,6 +48,32 @@ T remove_extension(T const& filename) {
     return p > 0 && p != T::npos ? filename.substr(0, p) : filename;
 }
 
+/**
+ * Retrun non-const iterator corresponding to the const_iterator in a vector
```
Comment (ohm314) [inline src/utils/common_utils.hpp:52]:
```suggestion
 * Return non-const iterator corresponding to the const_iterator in a vector
```

**Comment by cattabiani** [comment]
checking jenkins looks like there is some code left for debugging that prints the pythonpath for every test...

**Comment by pramodk** [comment]
> checking jenkins looks like there is some code left for debugging that prints the pythonpath for every test...

that might be just some old builds. I dont see any debug code into latest commits.
